export const theme = {
    colors: {
        white: '#FFFFFF',
        lightLightGrey: '#ededed',
        lightGrey: '#bfbfbf',
        grey: '#C0C7D6',
        darkGrey: '#737C8E',
        black: '#111111',
        success: '#8FCB81',
        successDark: '#0f9922',
        successDarkStrong: '#006400',
        error: '#FF8383',
        warning: '#E1D888',
        darkPurple: '#C0C7D6',
        lightPurple: '#f0f0f0',
        darkPro: '#2f3c4f',
        lightDarkPro: '#506e86',
        OrangePro: '#de703b',
        lightOrangePro: '#fcb040',
    },
    fontSize: {
        omegaBigBrother: '102px',
        omegaBig: '41px',
        xxl: '32px',
        xl: '25px',
        l_plus: '20px',
        l: '18px',
        m_plus: '16px',
        m: '15px',
        s: '14px',
        s_minus: '13px',
        micro_plus: '12px',
        micro: '10px',
    },
};
